### ISSUE TITLE
Find a different mumble image

### ISSUE THREAD

**Issue by white-gecko** [AKSW/poster-lobby.compose#1]
Maybe we can use some better mumble image as this one does not seem to receive updates anymore: https://github.com/coppit/docker-mumble-server/issues/2#issuecomment-317271878

> … (But I'm using Discord now, which is much better than Mumble.)

**Comment by ArkanEmre** [comment]
I found this [image](https://github.com/sudoforge/docker-images/tree/master/mumble-server). It seems to be well documented and gets updated frequently (see [sudoforge/mumble-server](https://github.com/sudoforge/docker-images/tree/master/mumble-server)). I also tested this, replacing the current image with this one. I haven't encountered any problems.

**Comment by white-gecko** [comment]
Closed with f1b39b41b897b6642d803e4e7c216ec3f4eb1dc2
